import Head from "next/head";
import { FunctionComponent } from "react";

interface LayoutProps{
    title:string,
    children:any,
}

const Layout:FunctionComponent<LayoutProps> = ({title,children}) => {
    return(
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="">
                {children}
            </div>
        </div>
    )
}

export default Layout;